elasticsearch:
  host: localhost
  port: 9200

spring:
  session:
    timeout: 86000
  data:
    redis:
      host: 10.10.32.91
      port: 6379
      password: 1234
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange:
    name: fanout-exchange
