### 스케줄 저장
POST http://localhost:8080/cron-job/register
Content-Type: application/json

{
  "scheduleJobSaveRequest": {
    "jobName": "memberUpdateJob",
    "jobGroup": "DEFAULT",
    "jobClassName": "com.example.quartz.member.MemberUpdateJobExecutor",
    "isDurable": false,
    "requestRecovery": true
  },
  "jobTriggerSaveRequest": {
    "jobName": "memberUpdateJob",
    "jobGroup": "DEFAULT",
    "triggerName": "MemberUpdateTrigger",
    "triggerGroup": "DEFAULT",
    "triggerType": "cron"
  },
  "cronTriggerSaveRequest": {
    "triggerName": "MemberUpdateTrigger",
    "triggerGroup": "DEFAULT",
    "timeZone" : "Asia/Seoul",
    "misFirePolicy" : "FIRE_AND_PROCEED",
    "cronExpressionRequest": {
      "frequency": "WEEKLY",
      "time": {
        "hour": 14,
        "minute": 0
      },
      "daysOfWeek": ["MON", "WED", "FRI"],
      "daysOfMonth": ["1", "15"],
      "specificDate": "2024-12-25"
    }
  }
}

### CronExpression 업데이트
POST http://localhost:8080/cron-expression/MemberUpdateTrigger/DEFAULT
Content-Type: application/json

{
  "frequency": "DAILY",
  "time": {
    "hour": 11,
    "minute": 49
  }
}

### 스케줄러 즉시 실행
POST http://localhost:8080/job-trigger/memberSaveJob/DEFAULT
