### 스케줄 저장
POST http://localhost:8080/job/register
Content-Type: application/json

{
  "scheduleJobSaveRequest": {
    "jobName": "memberSaveJob",
    "jobGroup": "DEFAULT",
    "jobClassName": "com.example.quartz.member.MemberSaveJobExecutor",
    "isDurable": false,
    "requestRecovery": true
  },
  "jobTriggerSaveRequest": {
    "jobName": "memberSaveJob",
    "triggerName": "MemberSaveTrigger",
    "triggerGroup": "DEFAULT",
    "triggerType": "cron"
  },
  "cronTriggerSaveRequest": {
    "triggerName": "MemberSaveTrigger",
    "triggerGroup": "DEFAULT",
    "cronExpression": "*/30 * * * * ?"
  }
}

### CronExpression 업데이트
POST http://localhost:8080/cron-expression/MemberSaveTrigger/DEFAULT
Content-Type: application/json

{
  "cronExpression": "*/10 * * * * ?"
}

### 스케줄러 즉시 실행
POST http://localhost:8080/job-trigger/memberSaveJob/DEFAULT
