### Job Detail 저장
POST http://localhost:8080/job-detail
Content-Type: application/json

{
  "jobName": "memberSaveJob",
  "jobGroup": "DEFAULT",
  "jobClassName": "com.example.quartz.member.MemberSaveJobExecutor",
  "isDurable": false,
  "requestRecovery": true
}

### Job Trigger 저장
POST http://localhost:8080/job-trigger
Content-Type: application/json

{
  "jobName" : "memberSaveJob",
  "triggerName" : "MemberSaveTrigger",
  "triggerGroup" : "DEFAULT",
  "triggerType": "cron"
}

### Job Cron Trigger 저장
POST http://localhost:8080/cron-trigger
Content-Type: application/json

{
  "triggerName" : "MemberSaveTrigger",
  "triggerGroup" : "DEFAULT",
  "cronExpression" : "*/15 * * * * ?"
}

### CronExpression 업데이트
POST http://localhost:8080/cron-expression/MemberSaveTrigger/DEFAULT
Content-Type: application/json

{
  "cronExpression": "*/15 * * * * ?"
}

### 스케줄러 즉시 실행
POST http://localhost:8080/job-trigger/memberSaveJob/DEFAULT
